### ISSUE TITLE
Use curly braces inside the markup template file

### ISSUE THREAD

**Issue by sasindu555** [wxlam/data-file-generator#5]
Hello,

Thank you for creating such a useful library.

I have an issue when generating files from my markup template file. In my markup template file, there are code blocks like this
`{{< plans-widget >}}`
`{{% login-widget %}}`

The output of each code block is this
`}`

I think it's messing up with keywords and braces. Is there a way to fix this problem?

Best regards,
Sasindu

**Comment by wxlam** [comment]
v0.8.16 - has been updated to handle custom delimiters, add the below to the config json:

```
  "customDelimiter": {
    "startsWith": "<<",
    "endsWith": ">>"
  },
```

if want to handle markup as `<<PARAM>>>`
